# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Iron Yard Charlotte -- Java Edition
email: ben.sterrett@theironyard.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website we'll be using to blog about our Charlotte Iron Yard Java cohorts!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/TIY-Charlotte-Java" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
